name: CI-CD

on:
  push:
    branches:
      - master

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: |
        cd web
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/resume-app:latest .

    - name: Push image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/resume-app:latest


  deploy_to_ec2:
    runs-on: ubuntu-latest
    needs: build_and_push_image

    steps:
    - name: Connect to EC2 with SSH & deploy
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker stop resume-app || true
          docker rm resume-app || true
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/resume-app:latest
          docker run -d -p 80:80 --name resume-app ${{ secrets.DOCKERHUB_USERNAME}}/resume-app:latest
